### ISSUE TITLE
releases

### ISSUE THREAD

**Issue by jney** [xvw/qian#17]
hi @xvw could you provide github releases? so i would create the associated brew formula?

**Comment by xvw** [comment]
By release, you wean ... "this" https://github.com/xvw/qian/releases ?

**Comment by jney** [comment]
yes. my bad

**Comment by xvw** [comment]
No problem, my answer could see "ironic" because I really suck in English :/ 
But I'm not an expert with git and github so, it was possible that i miss some points about the releasing of a project ;) 
Thanks a lot and feel free to make a PullRequest to update the readme if Qian is available on Brew !
